package com.woutwoot.jcwows.onlinetime;

import com.woutwoot.jcwows.tools.WootConfig;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;

import java.io.File;
import java.io.IOException;

public class UpdateTimesTask implements Runnable {

    private Plugin plugin;
    private WootConfig config;
    private int runCount = 0;

    public UpdateTimesTask(Plugin plugin) {
        this.plugin = plugin;
        config = new WootConfig(new File(plugin.getDataFolder() + File.separator + "data.times"));
    }

    @Override
    public void run() {
        runCount++;
        if (runCount == 1) {
            try {
                config.loadFile();
            } catch (IOException e) {
                plugin.getLogger().warning("Failed to load data file");
            }
        } else if (runCount % 2 == 0) {
            try {
                config.saveFile("Do not edit this file.");
            } catch (IOException e) {
                plugin.getLogger().warning("Failed to save data file");
            }
        }
        for (Player p : plugin.getServer().getOnlinePlayers()) {
            String id = p.getUniqueId().toString() + "(" + p.getName() + ")";
            int newTime = config.getInteger(id) + 2;

            if (newTime == 120) {
                //if(Main.getReferralSystem().isReferedPlayer(p)){
                //    Main.getReferralSystem().completeReferal(p);
                //}
            }

            this.config.setInteger(id, newTime);
        }
    }

}
